version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: devstore_postgres
    restart: always
    environment:
      POSTGRES_USER: devstore_user
      POSTGRES_PASSWORD: devstore_pass
      POSTGRES_DB: devstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: devstore_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: devstore_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  postgres_data:
  mongo_data:
